<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Demandeclient extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Demandeclient_model');
    } 

    /*
     * Listing of demandeclients
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('demandeclient/index?');
        $config['total_rows'] = $this->Demandeclient_model->get_all_demandeclients_count();
        $this->pagination->initialize($config);

        $data['demandeclients'] = $this->Demandeclient_model->get_all_demandeclients($params);
        
        $data['_view'] = 'demandeclient/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new demandeclient
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('date_demande','Date Demande','required');
		$this->form_validation->set_rules('nom_client','Nom Client','required');
		$this->form_validation->set_rules('motif_demande','Motif Demande','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'date_demande' => $this->input->post('date_demande'),
				'nom_client' => $this->input->post('nom_client'),
				'telephone' => $this->input->post('telephone'),
				'motif_demande' => $this->input->post('motif_demande'),
				'adresse' => $this->input->post('adresse'),
				'observation' => $this->input->post('observation'),
            );
            
            $demandeclient_id = $this->Demandeclient_model->add_demandeclient($params);
            redirect('demandeclient/index');
        }
        else
        {            
            $data['_view'] = 'demandeclient/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a demandeclient
     */
    function edit($dem_id)
    {   
        // check if the demandeclient exists before trying to edit it
        $data['demandeclient'] = $this->Demandeclient_model->get_demandeclient($dem_id);
        
        if(isset($data['demandeclient']['dem_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('date_demande','Date Demande','required');
			$this->form_validation->set_rules('nom_client','Nom Client','required');
			$this->form_validation->set_rules('motif_demande','Motif Demande','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'date_demande' => $this->input->post('date_demande'),
					'nom_client' => $this->input->post('nom_client'),
					'telephone' => $this->input->post('telephone'),
					'motif_demande' => $this->input->post('motif_demande'),
					'adresse' => $this->input->post('adresse'),
					'observation' => $this->input->post('observation'),
                );

                $this->Demandeclient_model->update_demandeclient($dem_id,$params);            
                redirect('demandeclient/index');
            }
            else
            {
                $data['_view'] = 'demandeclient/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The demandeclient you are trying to edit does not exist.');
    } 

    /*
     * Deleting demandeclient
     */
    function remove($dem_id)
    {
        $demandeclient = $this->Demandeclient_model->get_demandeclient($dem_id);

        // check if the demandeclient exists before trying to delete it
        if(isset($demandeclient['dem_id']))
        {
            $this->Demandeclient_model->delete_demandeclient($dem_id);
            redirect('demandeclient/index');
        }
        else
            show_error('The demandeclient you are trying to delete does not exist.');
    }
    
}
