<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Registredossier extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Registredossier_model');
    } 

    /*
     * Listing of registredossiers
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('registredossier/index?');
        $config['total_rows'] = $this->Registredossier_model->get_all_registredossiers_count();
        $this->pagination->initialize($config);

        $data['registredossiers'] = $this->Registredossier_model->get_all_registredossiers($params);
        
        $data['_view'] = 'registredossier/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new registredossier
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'declarant_sid' => $this->input->post('declarant_sid'),
				'numDossier' => $this->input->post('numDossier'),
				'paysProv' => $this->input->post('paysProv'),
				'lieuEntree' => $this->input->post('lieuEntree'),
				'dateEntree' => $this->input->post('dateEntree'),
				'nationTransp' => $this->input->post('nationTransp'),
				'modeTransp' => $this->input->post('modeTransp'),
				'valeurDouane' => $this->input->post('valeurDouane'),
				'DroitPercu' => $this->input->post('DroitPercu'),
				'entrepot' => $this->input->post('entrepot'),
				'apurement' => $this->input->post('apurement'),
				'liquidation' => $this->input->post('liquidation'),
				'observation' => $this->input->post('observation'),
            );
            
            $registredossier_id = $this->Registredossier_model->add_registredossier($params);
            redirect('registredossier/index');
        }
        else
        {
			$this->load->model('Declarant_model');
			$data['all_declarants'] = $this->Declarant_model->get_all_declarants();
            
            $data['_view'] = 'registredossier/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a registredossier
     */
    function edit($dossier_id)
    {   
        // check if the registredossier exists before trying to edit it
        $data['registredossier'] = $this->Registredossier_model->get_registredossier($dossier_id);
        
        if(isset($data['registredossier']['dossier_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'declarant_sid' => $this->input->post('declarant_sid'),
					'numDossier' => $this->input->post('numDossier'),
					'paysProv' => $this->input->post('paysProv'),
					'lieuEntree' => $this->input->post('lieuEntree'),
					'dateEntree' => $this->input->post('dateEntree'),
					'nationTransp' => $this->input->post('nationTransp'),
					'modeTransp' => $this->input->post('modeTransp'),
					'valeurDouane' => $this->input->post('valeurDouane'),
					'DroitPercu' => $this->input->post('DroitPercu'),
					'entrepot' => $this->input->post('entrepot'),
					'apurement' => $this->input->post('apurement'),
					'liquidation' => $this->input->post('liquidation'),
					'observation' => $this->input->post('observation'),
                );

                $this->Registredossier_model->update_registredossier($dossier_id,$params);            
                redirect('registredossier/index');
            }
            else
            {
				$this->load->model('Declarant_model');
				$data['all_declarants'] = $this->Declarant_model->get_all_declarants();

                $data['_view'] = 'registredossier/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The registredossier you are trying to edit does not exist.');
    } 

    /*
     * Deleting registredossier
     */
    function remove($dossier_id)
    {
        $registredossier = $this->Registredossier_model->get_registredossier($dossier_id);

        // check if the registredossier exists before trying to delete it
        if(isset($registredossier['dossier_id']))
        {
            $this->Registredossier_model->delete_registredossier($dossier_id);
            redirect('registredossier/index');
        }
        else
            show_error('The registredossier you are trying to delete does not exist.');
    }
    
}
