<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bonlivraison_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bonlivraison by bon_id
     */
    function get_bonlivraison($bon_id)
    {
        return $this->db->get_where('bonlivraisons',array('bon_id'=>$bon_id))->row_array();
    }
    
    /*
     * Get all bonlivraisons count
     */
    function get_all_bonlivraisons_count()
    {
        $this->db->from('bonlivraisons');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all bonlivraisons
     */
    function get_all_bonlivraisons($params = array())
    {
        $this->db->order_by('bon_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('bonlivraisons')->result_array();
    }
        
    /*
     * function to add new bonlivraison
     */
    function add_bonlivraison($params)
    {
        $this->db->insert('bonlivraisons',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bonlivraison
     */
    function update_bonlivraison($bon_id,$params)
    {
        $this->db->where('bon_id',$bon_id);
        return $this->db->update('bonlivraisons',$params);
    }
    
    /*
     * function to delete bonlivraison
     */
    function delete_bonlivraison($bon_id)
    {
        return $this->db->delete('bonlivraisons',array('bon_id'=>$bon_id));
    }
}
