<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cotation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cotation by 
     */
    function get_cotation($id)
    {
        return $this->db->get_where('cotations',array('cot_id'=>$id))->row_array();
    }
    
    /*
     * Get all cotations count
     */
    function get_all_cotations_count()
    {
        $this->db->from('cotations');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all cotations
     */
    function get_all_cotations($params = array())
    {
        $this->db->order_by('', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('cotations')->result_array();
    }
        
    /*
     * function to add new cotation
     */
    function add_cotation($params)
    {
        $this->db->insert('cotations',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cotation
     */
    function update_cotation($id,$params)
    {
        $this->db->where('cot_id',$id);
        return $this->db->update('cotations',$params);
    }
    
    /*
     * function to delete cotation
     */
    function delete_cotation($id)
    {
        return $this->db->delete('cotations',array('cot_id'=>$id));
    }
}
