<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Declarant_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get declarant by matricule
     */
    function get_declarant($matricule)
    {
        return $this->db->get_where('declarants',array('matricule'=>$matricule))->row_array();
    }
    
    /*
     * Get all declarants count
     */
    function get_all_declarants_count()
    {
        $this->db->from('declarants');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all declarants
     */
    function get_all_declarants($params = array())
    {
        $this->db->order_by('matricule', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('declarants')->result_array();
    }
        
    /*
     * function to add new declarant
     */
    function add_declarant($params)
    {
        $this->db->insert('declarants',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update declarant
     */
    function update_declarant($matricule,$params)
    {
        $this->db->where('matricule',$matricule);
        return $this->db->update('declarants',$params);
    }
    
    /*
     * function to delete declarant
     */
    function delete_declarant($matricule)
    {
        return $this->db->delete('declarants',array('matricule'=>$matricule));
    }
}
