<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Demandeclient_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get demandeclient by dem_id
     */
    function get_demandeclient($dem_id)
    {
        return $this->db->get_where('demandeclients',array('dem_id'=>$dem_id))->row_array();
    }
    
    /*
     * Get all demandeclients count
     */
    function get_all_demandeclients_count()
    {
        $this->db->from('demandeclients');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all demandeclients
     */
    function get_all_demandeclients($params = array())
    {
        $this->db->order_by('dem_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('demandeclients')->result_array();
    }
        
    /*
     * function to add new demandeclient
     */
    function add_demandeclient($params)
    {
        $this->db->insert('demandeclients',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update demandeclient
     */
    function update_demandeclient($dem_id,$params)
    {
        $this->db->where('dem_id',$dem_id);
        return $this->db->update('demandeclients',$params);
    }
    
    /*
     * function to delete demandeclient
     */
    function delete_demandeclient($dem_id)
    {
        return $this->db->delete('demandeclients',array('dem_id'=>$dem_id));
    }
}
