<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Registredossier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get registredossier by dossier_id
     */
    function get_registredossier($dossier_id)
    {
        return $this->db->get_where('registredossiers',array('dossier_id'=>$dossier_id))->row_array();
    }
    
    /*
     * Get all registredossiers count
     */
    function get_all_registredossiers_count()
    {
        $this->db->from('registredossiers');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all registredossiers
     */
    function get_all_registredossiers($params = array())
    {
        $this->db->order_by('dossier_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('registredossiers')->result_array();
    }
        
    /*
     * function to add new registredossier
     */
    function add_registredossier($params)
    {
        $this->db->insert('registredossiers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update registredossier
     */
    function update_registredossier($dossier_id,$params)
    {
        $this->db->where('dossier_id',$dossier_id);
        return $this->db->update('registredossiers',$params);
    }
    
    /*
     * function to delete registredossier
     */
    function delete_registredossier($dossier_id)
    {
        return $this->db->delete('registredossiers',array('dossier_id'=>$dossier_id));
    }
}
